name 'zoide-ganglia'
version '2.0'
author 'Udo Waechter <do@maketank.net>'
license 'GPL'
dependency 'camptocamp/git', '>=0'
dependency 'puppetlabs/stdlib', '>=0'
project_page 'https://github.com/zoide/puppet-ganglia'
source 'git@github.com:zoide/puppet-ganglia.git'
summary 'Manage a complete ganglia infrastructure.'
description ''
